# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(519, 159)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pathbutton = QtWidgets.QPushButton(self.centralwidget)
        self.pathbutton.setEnabled(True)
        self.pathbutton.setGeometry(QtCore.QRect(10, 80, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pathbutton.setFont(font)
        self.pathbutton.setObjectName("pathbutton")
        self.linkline = QtWidgets.QLineEdit(self.centralwidget)
        self.linkline.setGeometry(QtCore.QRect(120, 20, 391, 20))
        self.linkline.setObjectName("linkline")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.sendbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sendbutton.setGeometry(QtCore.QRect(400, 120, 111, 31))
        self.sendbutton.setObjectName("sendbutton")
        self.pathline = QtWidgets.QLineEdit(self.centralwidget)
        self.pathline.setEnabled(False)
        self.pathline.setGeometry(QtCore.QRect(160, 80, 351, 31))
        self.pathline.setObjectName("pathline")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.archiveline = QtWidgets.QLineEdit(self.centralwidget)
        self.archiveline.setGeometry(QtCore.QRect(120, 50, 391, 20))
        self.archiveline.setObjectName("archiveline")
        self.resultline = QtWidgets.QLineEdit(self.centralwidget)
        self.resultline.setEnabled(False)
        self.resultline.setGeometry(QtCore.QRect(10, 120, 371, 31))
        self.resultline.setObjectName("resultline")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GeradorExcel"))
        self.pathbutton.setText(_translate("MainWindow", "Escolher caminho"))
        self.label.setText(_translate("MainWindow", "Digite o link:"))
        self.sendbutton.setText(_translate("MainWindow", "Gerar Arquivo Excel"))
        self.label_3.setText(_translate("MainWindow", "Nome do arquivo:"))
